name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-12.0
          - os: ubuntu-20.04
    steps:
      - uses: fwal/setup-swift@v1.14.0
        with:
          swift-version: "5.6"
      - run: swift --version
      - uses: actions/checkout@v2

      -
        run: swift test

      -
        run: swift build -c release
